name: Deploy EC2 Stack
on: [push]

jobs:
  Deploy-EC2-Stack:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      # Enable debug logging
      - name: Enable Debug Logging
        run: echo "AWS_SDK_LOAD_CONFIG=1" >> $GITHUB_ENV

      # Authenticate using OIDC
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::849059301510:role/github-action-deploy
          aws-region: eu-north-1

      # Log AWS identity to verify OIDC authentication
      - name: Verify AWS Identity
        run: aws sts get-caller-identity

      # Check out repository code
      - name: Check out repository code
        uses: actions/checkout@v4

      # Print current directory
      - name: Print current directory files
        run: ls

      # Deploy the CloudFormation stack
      - name: Deploy CloudFormation Stack
        run: |
          aws cloudformation deploy \
            --template-file ./ec2.yml \
            --stack-name EC2Stack \
            --capabilities CAPABILITY_NAMED_IAM

      # Retrieve the public IP of the EC2 instance
      - name: Get EC2 Instance ID
        id: get-ec2-id
        run: |
          INSTANCE_ID=$(aws cloudformation describe-stack-resources \
          --stack-name EC2Stack \
          --query "StackResources[?LogicalResourceId=='EC2Instance'].PhysicalResourceId" \
          --output text)
          echo "INSTANCE_ID=$INSTANCE_ID" >> $GITHUB_ENV

      # Wait for EC2 instance to be ready
      - name: Wait for EC2 Instance
        run: sleep 60

      # Deploy code to EC2 via SSM
      - name: Deploy Code to EC2 via SSM
        run: |
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --targets "Key=instanceIds,Values=${{ env.INSTANCE_ID }}" \
            --parameters '{"commands":["#!/bin/bash", "set -e", "echo Cloning the repository...", "git clone https://github.com/agrajy10/ci-cd-frontend.git", "cd ci-cd-frontend", "echo Installing dependencies...", "npm install", "echo Building the Vite React project...", "npm run build", "echo Installing serve to serve the build...", "npm install -g serve", "echo Serving the build...", "sudo pkill -f serve || true", "nohup serve -s build -l 80 &", "echo Deployment completed successfully."]}' \
            --region eu-north-1
