name: Deploy EC2 Stack
on: [push]

jobs:
  Deploy-EC2-Stack:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      # Authenticate using OIDC
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::849059301510:role/github-action-deploy-role
          aws-region: eu-north-1

      # Check out repository code
      - name: Check out repository code
        uses: actions/checkout@v4

      # Print current directory
      - name: Print current directory
        run: pwd

      # Deploy the CloudFormation stack
      - name: Deploy CloudFormation Stack
        run: |
          aws cloudformation deploy \
            --template-file c:/ci-cd-practice/ci-cd-frontend/ec2.yml \
            --stack-name EC2Stack \
            --capabilities CAPABILITY_NAMED_IAM
